apiVersion: v1
kind: Pod
metadata:
  name: test-nginx 
spec:
  containers:
  - image: nginx
    name: nginx
    volumeMounts:
    - mountPath: /data
      name: test-volume
  volumes:
  - name: test-volume
    hostPath:
      # directory location on host
      path: /home/dlt/data
      type: Directory
